---
- name: dnf_clean
  command: dnf clean all
  changed_when: false   

- name: firewalld_reload
  firewalld:
    state: reloaded
    immediate: yes      
  changed_when: false   

- name: stop_maria
  systemd:
    name: mariadb
    state: stopped
